name: "Upload cypress to BrowserStack"

on: [push]
jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest # Can be self-hosted runner also
    steps:
          
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: 'BrowserStack Local Tunnel Setup'  # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-logging-level: all-logs
          local-identifier: random
          local-args: --force-proxy

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
            
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with: 
          command: npm run cypress:browserstack #command browserstack

      - name: 'BrowserStackLocal Stop'  # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop